version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pass123
    restart: always
    ports:
      - "5432:5432"
  test-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pass123
    restart: always
    ports:
      - "5434:5432"
